// // 'use client'
// import localFont from "next/font/local";
// import "./globals.css";
// import Header from "@/components/Header";
// import Footer from "@/components/newcomponents/Footer.jsx";
// // import { usePathname } from "next/navigation";
//
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
//
// export const metadata = {
//   title: "hospital mangement",
//   description: "Generated by create next app",
// };
//
// export default function RootLayout({ children }) {
//     // const pathname = usePathname();
//
//     // const hideNavbar =
//     //     pathname.startsWith("/DoctorHome");
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//       {/*{!hideNavbar &&  <Header /> }*/}
//       <Header />
//         {children}
//       <Footer />
//       </body>
//     </html>
//   );
// }
"use client";

import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/newcomponents/Footer.jsx";
import { usePathname } from "next/navigation";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export default function RootLayout({ children }) {
    const pathname = usePathname();

    const hideLayout = pathname.startsWith("/forms");

    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        {!hideLayout && <Header />}

        {children}

        {!hideLayout && <Footer />}

        </body>
        </html>
    );
}
